version: '3.7'

services:
  web:
    image: 'api'
    build:
      context: ./Eventnet/
      dockerfile: Eventnet.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=eventnet;User Id=postgres;Password=1234;
    ports:
      - 5203:80
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres
    environment:
      - POSTGRES_DB=eventnet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_PORT=5432
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
